/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Ecowallet } from "./Ecowallet";
export * as factories from "./factories";
export { Ecowallet__factory } from "./factories/Ecowallet__factory";
